"""Add image1..image4 to Project

Revision ID: 003d4b407a3e
Revises: 03195a770cc9
Create Date: 2025-10-04 13:11:12.674803

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '003d4b407a3e'
down_revision = '03195a770cc9'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('project', schema=None) as batch_op:
        batch_op.add_column(sa.Column('image1', sa.String(length=200), nullable=True))
        batch_op.add_column(sa.Column('image2', sa.String(length=200), nullable=True))
        batch_op.add_column(sa.Column('image3', sa.String(length=200), nullable=True))
        batch_op.add_column(sa.Column('image4', sa.String(length=200), nullable=True))
        batch_op.drop_column('image')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('project', schema=None) as batch_op:
        batch_op.add_column(sa.Column('image', sa.VARCHAR(length=200), nullable=True))
        batch_op.drop_column('image4')
        batch_op.drop_column('image3')
        batch_op.drop_column('image2')
        batch_op.drop_column('image1')

    # ### end Alembic commands ###
