"""Add bibtex to Publications

Revision ID: 79d8e864d8e0
Revises: 003d4b407a3e
Create Date: 2025-10-04 15:15:09.596483

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '79d8e864d8e0'
down_revision = '003d4b407a3e'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('lab_info', schema=None) as batch_op:
        batch_op.drop_column('focus_statement')

    with op.batch_alter_table('publication', schema=None) as batch_op:
        batch_op.add_column(sa.Column('bibtex', sa.Text(), nullable=False))
        batch_op.alter_column('title',
               existing_type=sa.VARCHAR(length=500),
               nullable=True)
        batch_op.alter_column('authors',
               existing_type=sa.VARCHAR(length=500),
               nullable=True)

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('publication', schema=None) as batch_op:
        batch_op.alter_column('authors',
               existing_type=sa.VARCHAR(length=500),
               nullable=False)
        batch_op.alter_column('title',
               existing_type=sa.VARCHAR(length=500),
               nullable=False)
        batch_op.drop_column('bibtex')

    with op.batch_alter_table('lab_info', schema=None) as batch_op:
        batch_op.add_column(sa.Column('focus_statement', sa.TEXT(), nullable=True))

    # ### end Alembic commands ###
